# Generated by Django 4.0 on 2022-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999, verbose_name='Title')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('keywords', models.TextField(verbose_name='Keywords')),
                ('description', models.TextField(default='a short description', verbose_name='Description')),
            ],
        ),
    ]
