# Generated by Django 4.0.2 on 2022-03-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='desription',
        ),
        migrations.AddField(
            model_name='articles',
            name='description',
            field=models.TextField(default='a short description', verbose_name='Description'),
        ),
    ]
