# Generated by Django 4.0 on 2022-03-10 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomizedUserModel', '0001_initial'),
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomizedUserModel.userperson', verbose_name='Writer'),
        ),
    ]
