# Generated by Django 3.0 on 2022-04-26 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Articles', '0001_initial'),
        ('CustomizedUserModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleslikes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomizedUserModel.Userperson', verbose_name='Like'),
        ),
        migrations.AddField(
            model_name='articleshits',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Articles.Articles', verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='articlescomments',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.Articles', verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='articlescomments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomizedUserModel.Userperson', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='articles',
            name='labels',
            field=models.ManyToManyField(to='Articles.ArticlesLabels', verbose_name='Labels'),
        ),
        migrations.AddField(
            model_name='articles',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomizedUserModel.Userperson', verbose_name='Writer'),
        ),
    ]
