# Generated by Django 4.0 on 2022-04-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlescomments',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='articlescomments',
            name='last_name',
        ),
    ]
