# Generated by Django 4.0 on 2022-04-17 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomizedUserModel', '0001_initial'),
        ('Articles', '0003_remove_articlescomments_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlescomments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomizedUserModel.userperson', verbose_name='User'),
        ),
    ]
