# Generated by Django 4.0 on 2022-03-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_articles_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesHits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='IP')),
            ],
        ),
    ]
