# Generated by Django 4.0 on 2022-04-20 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomizedUserModel', '0001_initial'),
        ('Articles', '0004_alter_articlescomments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleslikes',
            name='like',
        ),
        migrations.AddField(
            model_name='articleslikes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomizedUserModel.userperson', verbose_name='Like'),
        ),
    ]
