# Generated by Django 4.0 on 2022-03-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0006_articles_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.TextField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
