# Generated by Django 4.0 on 2022-03-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0007_alter_articles_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='labels',
            field=models.ManyToManyField(to='Articles.ArticlesLabels', verbose_name='Labels'),
        ),
    ]
