# Generated by Django 4.0 on 2022-03-12 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomizedUserModel', '0001_initial'),
        ('Articles', '0010_articles_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='likes',
        ),
        migrations.CreateModel(
            name='ArticlesLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomizedUserModel.userperson', verbose_name='Like')),
            ],
        ),
    ]
