# Generated by Django 4.0 on 2022-03-12 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0011_remove_articles_likes_articleslikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleslikes',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Articles.articles', verbose_name='Article'),
        ),
    ]
