# Generated by Django 4.0 on 2022-03-12 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomizedUserModel', '0001_initial'),
        ('Articles', '0012_articleslikes_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomizedUserModel.userperson', verbose_name='User')),
            ],
        ),
    ]
