# Generated by Django 4.0 on 2022-03-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0013_articlescomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescomments',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Articles.articles', verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='articlescomments',
            name='first_name',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='articlescomments',
            name='last_name',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='articlescomments',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Status'),
        ),
    ]
