# Generated by Django 4.0 on 2022-04-19 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomizedUserModel', '0001_initial'),
        ('Products', '0001_initial'),
        ('Carts', '0001_initial'),
        ('Sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='category',
            field=models.ManyToManyField(to='Products.ProductSubCategories_1', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='orders',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellers.sellers', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='carts',
            name='shoper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomizedUserModel.userperson', verbose_name='Shoper'),
        ),
    ]
