# Generated by Django 4.0 on 2022-03-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Product id'),
        ),
    ]
