# Generated by Django 4.0.4 on 2022-04-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sellers', '0002_rename_vendorcategories_sellerscategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerscategories',
            name='status',
        ),
    ]
