# Generated by Django 4.0 on 2022-03-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='melipayamak_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Melipayamak Password'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='melipayamak_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Melipayamak Phone'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='melipayamak_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Melipayamak Username'),
        ),
    ]
