# Generated by Django 4.0.2 on 2022-02-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullname', models.CharField(max_length=100, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone')),
                ('image', models.ImageField(blank=True, null=True, upload_to='userphoto/fullname', verbose_name='User Photo')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone_auth', models.BooleanField(default=False, verbose_name='Phone Auth')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=50, verbose_name='Gender')),
                ('role', models.CharField(choices=[('seller', 'Seller'), ('shopper', 'Shopper'), ('serviceman', 'Serviceman')], max_length=50, verbose_name='Rols')),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Super User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
