# Generated by Django 4.0 on 2022-03-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomizedUserModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperson',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('seller', 'Seller'), ('shopper', 'Shopper'), ('serviceman', 'Serviceman')], max_length=50, verbose_name='Rols'),
        ),
    ]
