# Generated by Django 4.0 on 2022-04-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomizedUserModel', '0003_alter_userperson_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperson',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('seller', 'Seller'), ('serviceman', 'Serviceman')], max_length=50, verbose_name='Rols'),
        ),
    ]
