# Generated by Django 4.0 on 2022-03-11 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sellers', '0001_initial'),
        ('CustomizedUserModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMainCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, verbose_name='Name')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=999, null=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=999)),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('discounted_price', models.IntegerField(blank=True, null=True, verbose_name='Discounted Price')),
                ('score', models.IntegerField(default=1, verbose_name='Score')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('inventory', models.IntegerField(verbose_name='Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('color_code', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategories_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, verbose_name='Name')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategories_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, verbose_name='Name')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('product_main_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productmaincategories', verbose_name='Product Main Categories')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsTrackingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=150, verbose_name='Tracking Code')),
                ('code_status', models.BooleanField(verbose_name='Code Status')),
                ('product_status', models.CharField(choices=[('confirming', 'در حال تایید'), ('confirmed', 'تایید شده'), ('sending', 'در حال ارسال'), ('processed', 'اتمام')], max_length=100, verbose_name='Product_status')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(verbose_name='"Total Score')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Products.products', verbose_name='Prodcut ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products', verbose_name='Prodcut Id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomizedUserModel.userperson', verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(to='Products.ProductSubCategories_1', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellers.sellers', verbose_name='Seller'),
        ),
    ]
