# Generated by Django 4.0 on 2022-04-17 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sellers', '0001_initial'),
        ('CustomizedUserModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMainCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ProductMainCategoriesImage', verbose_name='Image')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=999, null=True, verbose_name='Title')),
                ('slug', models.TextField(max_length=999)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='productsImage', verbose_name='Image')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='productsImage', verbose_name='Image1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='productsImage', verbose_name='Image2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='productsImage', verbose_name='Image3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='productsImage', verbose_name='Image4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='productsImage', verbose_name='Image5')),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Short Description')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('discounted_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Discounted Price')),
                ('score', models.IntegerField(default=1, verbose_name='Score')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('inventory', models.IntegerField(default=0, verbose_name='Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ProductsSlides', verbose_name='Image')),
                ('url', models.URLField(verbose_name='Url')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategories_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, verbose_name='Name')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategories_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, verbose_name='Name')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('sub_categories2', models.ManyToManyField(blank=True, to='Products.ProductSubCategories_2', verbose_name='Sub Categories 2')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsTrackingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=150, verbose_name='Tracking Code')),
                ('code_status', models.BooleanField(verbose_name='Code Status')),
                ('product_status', models.CharField(choices=[('confirming', 'در حال تایید'), ('confirmed', 'تایید شده'), ('sending', 'در حال ارسال'), ('processed', 'اتمام')], max_length=100, verbose_name='Product_status')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(verbose_name='"Total Score')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Products.products', verbose_name='Prodcut ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('product_image', models.ImageField(upload_to='ProductsCommentsImage', verbose_name='Image')),
                ('product_title', models.TextField(verbose_name='Title')),
                ('product_short_description', models.TextField(verbose_name='Short description')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products', verbose_name='Prodcut Id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomizedUserModel.userperson', verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='colors',
            field=models.ManyToManyField(blank=True, to='Products.ProductsColor', verbose_name='Colors'),
        ),
        migrations.AddField(
            model_name='products',
            name='maincategories',
            field=models.ManyToManyField(blank=True, to='Products.ProductMainCategories', verbose_name='Main Category'),
        ),
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellers.sellers', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='products',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='Products.ProductsSizes', verbose_name='Sizes'),
        ),
        migrations.AddField(
            model_name='products',
            name='subCategories1',
            field=models.ManyToManyField(blank=True, to='Products.ProductSubCategories_1', verbose_name='Sub Category 1'),
        ),
        migrations.AddField(
            model_name='products',
            name='subCategories2',
            field=models.ManyToManyField(blank=True, to='Products.ProductSubCategories_2', verbose_name='Sub Category 2'),
        ),
        migrations.AddField(
            model_name='productmaincategories',
            name='sub_categories1',
            field=models.ManyToManyField(blank=True, to='Products.ProductSubCategories_1', verbose_name='Sub Categories 1'),
        ),
    ]
