# Generated by Django 4.0 on 2022-04-18 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sellers.sellers', verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='products',
            name='sizes',
            field=models.ManyToManyField(to='Products.ProductsSizes', verbose_name='Sizes'),
        ),
        migrations.AddField(
            model_name='products',
            name='subCategories1',
            field=models.ManyToManyField(blank=True, to='Products.ProductSubCategories_1', verbose_name='Sub Category 1'),
        ),
        migrations.AddField(
            model_name='products',
            name='subCategories2',
            field=models.ManyToManyField(blank=True, to='Products.ProductSubCategories_2', verbose_name='Sub Category 2'),
        ),
        migrations.AddField(
            model_name='productmaincategories',
            name='sub_categories1',
            field=models.ManyToManyField(blank=True, to='Products.ProductSubCategories_1', verbose_name='Sub Categories 1'),
        ),
    ]
