# Generated by Django 4.0 on 2022-03-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='total_score',
            field=models.IntegerField(verbose_name='"Total Score'),
        ),
    ]
