# Generated by Django 4.0 on 2022-04-17 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomizedUserModel', '0001_initial'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscomments',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='productscomments',
            name='product_short_description',
        ),
        migrations.RemoveField(
            model_name='productscomments',
            name='product_title',
        ),
        migrations.AlterField(
            model_name='productscomments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomizedUserModel.userperson', verbose_name='User'),
        ),
    ]
