# Generated by Django 4.0 on 2022-03-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productsImage', verbose_name='Image'),
        ),
    ]
