# Generated by Django 4.0 on 2022-04-25 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomizedUserModel', '0001_initial'),
        ('Products', '0002_rename_productsslides_productssliders'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsscores',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomizedUserModel.userperson', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='productsscores',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products', verbose_name='Prodcut'),
        ),
    ]
