# Generated by Django 4.0 on 2022-04-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='maincategories',
            field=models.ManyToManyField(to='Products.ProductMainCategories', verbose_name='Main Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='subCategories1',
            field=models.ManyToManyField(to='Products.ProductSubCategories_1', verbose_name='Sub Category 1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='subCategories2',
            field=models.ManyToManyField(to='Products.ProductSubCategories_2', verbose_name='Sub Category 2'),
        ),
    ]
