# Generated by Django 4.0 on 2022-03-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, to='Products.ProductsColor', verbose_name='Colors'),
        ),
    ]
