# Generated by Django 4.0 on 2022-04-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_productsscores_user_alter_productsscores_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsscores',
            old_name='total_score',
            new_name='score',
        ),
    ]
