# Generated by Django 4.0 on 2022-03-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_tesyy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tesYY',
        ),
    ]
