# Generated by Django 4.0 on 2022-04-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_products_colors_alter_products_maincategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.TextField(unique=True),
        ),
    ]
