# Generated by Django 4.0 on 2022-03-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_products_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discounted_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Discounted Price'),
        ),
    ]
