# Generated by Django 4.0 on 2022-03-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_products_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaincategories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ProductMainCategoriesImage', verbose_name='Image'),
        ),
    ]
