# Generated by Django 4.0 on 2022-03-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_productmaincategories_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ProductsSlides', verbose_name='Image')),
                ('url', models.URLField(verbose_name='Url')),
            ],
        ),
    ]
