# Generated by Django 4.0 on 2022-04-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='colors',
            field=models.ManyToManyField(to='Products.ProductsColor', verbose_name='Colors'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discounted_price',
            field=models.IntegerField(verbose_name='Discounted Price'),
        ),
        migrations.AlterField(
            model_name='products',
            name='inventory',
            field=models.IntegerField(verbose_name='Inventory'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sizes',
            field=models.ManyToManyField(to='Products.ProductsSizes', verbose_name='Sizes'),
        ),
    ]
