# Generated by Django 4.0 on 2022-03-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_productsslides'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productscolor',
            old_name='color_code',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='products',
            name='colors',
            field=models.ManyToManyField(blank=True, to='Products.ProductsColor', verbose_name='Colors'),
        ),
    ]
