# Generated by Django 4.0 on 2022-03-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_rename_color_code_productscolor_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
