# Generated by Django 4.0 on 2022-04-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_alter_products_colors_alter_products_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sizes',
            field=models.ManyToManyField(to='Products.ProductsSizes', verbose_name='Sizes'),
        ),
    ]
