# Generated by Django 4.0 on 2022-03-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_products_sizes_alter_products_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Short Description'),
        ),
    ]
