# Generated by Django 4.0 on 2022-03-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_productsphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscomments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='productscomments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ProductsCommentsImage', verbose_name='Image'),
        ),
    ]
