# Generated by Django 4.0 on 2022-03-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_productscomments_date_productscomments_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productscomments',
            old_name='image',
            new_name='product_image',
        ),
        migrations.AddField(
            model_name='productscomments',
            name='product_title',
            field=models.TextField(blank=True, null=True, verbose_name='Title'),
        ),
    ]
