# Generated by Django 4.0 on 2022-03-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_rename_image_productscomments_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscomments',
            name='product_short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
    ]
