# Generated by Django 4.0 on 2022-04-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_rename_image_products_main_image_products_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubcategories_1',
            name='product_main_categories',
        ),
        migrations.AddField(
            model_name='productmaincategories',
            name='subCategories_1',
            field=models.ManyToManyField(blank=True, null=True, to='Products.ProductSubCategories_1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='Products.ProductMainCategories', verbose_name='Category'),
        ),
    ]
