# Generated by Django 4.0 on 2022-04-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_remove_productsubcategories_1_product_main_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaincategories',
            name='subCategories_1',
            field=models.ManyToManyField(blank=True, to='Products.ProductSubCategories_1', verbose_name='ProductSubCategories_1'),
        ),
    ]
