# Generated by Django 4.0 on 2022-04-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_alter_productmaincategories_subcategories_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, to='Products.ProductMainCategories', verbose_name='Category'),
        ),
    ]
