# Generated by Django 4.0 on 2022-04-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0019_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaincategories',
            name='subCategories_1',
            field=models.ManyToManyField(blank=True, related_name='ProductSubCategories1', to='Products.ProductSubCategories_1', verbose_name='ProductSubCategories_1'),
        ),
    ]
