# Generated by Django 4.0 on 2022-04-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0020_alter_productmaincategories_subcategories_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaincategories',
            name='subCategories_1',
            field=models.ManyToManyField(blank=True, to='Products.ProductSubCategories_1', verbose_name='ProductSubCategories_1'),
        ),
    ]
